name: CI

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test-linux:
    name: Test and coverage (Linux)
    strategy:
      matrix:
        go-version: ["1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Run CI (tidy, lint, test, coverage)
        run: make ci
        env:
          MIN_COVER: "70.0"

      - name: Upload coverage to Codecov
        if: ${{ matrix.go-version == '1.24' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          flags: unittests
          fail_ci_if_error: true
          verbose: true
